[build]
base = ""
publish = "public"
command = "AWS_LAMBDA_FUNCTION_NAME=trickpuppeteer npm run build"

[functions]
node_bundler = "esbuild"

[functions.preview]
included_files = [
"./netlify/functions/preview/**/*",
"./netlify/functions/preview/.cache/**/*"
]

[[redirects]]
from = "/preview/:uid/"
to = "/.netlify/functions/preview"
status = 200
force = true
_generated_by_eleventy_serverless = "preview"
